/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.swing.myproject.GUI;


import com.swing.myproject.service.impl.ActionService;
import com.swing.myproject.service.impl.CheckService;
import com.swing.myproject.service.impl.PreconditionService;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author nmthang
 */
public class HomeGUI extends javax.swing.JFrame {

    private static int tab = -1;
    private static HomeGUI homeGUI;
    private ImportGUI importGUI;

    public HomeGUI() {
        initComponents();
        this.importGUI = new ImportGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        tablePanel = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        preItem = new javax.swing.JMenuItem();
        actItem = new javax.swing.JMenuItem();
        checkItem = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(185, 220, 254));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(218, 236, 254));

        tablePanel.setBackground(new java.awt.Color(172, 172, 172));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1036, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Import File");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        viewMenu.setText("View");

        jMenuItem6.setText("All");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        viewMenu.add(jMenuItem6);

        preItem.setText("Precondition");
        preItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preItemActionPerformed(evt);
            }
        });
        viewMenu.add(preItem);

        actItem.setText("Action");
        actItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actItemActionPerformed(evt);
            }
        });
        viewMenu.add(actItem);

        checkItem.setText("Check");
        checkItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkItemActionPerformed(evt);
            }
        });
        viewMenu.add(checkItem);

        jMenu8.setText("Other...");

        jMenuItem10.setText("Heading");
        jMenu8.add(jMenuItem10);

        jMenuItem11.setText("TC_ID");
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("Label");
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Signal");
        jMenu8.add(jMenuItem13);

        viewMenu.add(jMenu8);

        jMenuBar1.add(viewMenu);

        jMenu3.setText("Option");
        jMenuBar1.add(jMenu3);

        jMenu7.setText("Tools");
        jMenuBar1.add(jMenu7);

        jMenu6.setText("Help");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.importGUI.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void checkItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkItemActionPerformed
        // TODO add your handling code here:
        CheckService check = new CheckService();
        String[] header = {"Row", "TC_ID", "Heading", "Check"};
        Object[][] content = check.findAll();
        createTable(header, content, "Check");
    }//GEN-LAST:event_checkItemActionPerformed

    private void preItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preItemActionPerformed
        PreconditionService pre = new PreconditionService();
        String[] header = {"Row", "TC_ID", "Heading", "Precondition"};
        Object[][] content = pre.findAll();
        createTable(header, content, "Precondition");
    }//GEN-LAST:event_preItemActionPerformed

    private void actItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actItemActionPerformed
        // TODO add your handling code here:
        ActionService act = new ActionService();
        String[] header = {"Row", "TC_ID", "Heading", "Action"};
        Object[][] content = act.findAll();
        createTable(header, content, "Action");
    }//GEN-LAST:event_actItemActionPerformed

    private void createTable(String[] header, Object[][] content, String nameTab) {
        tab += 1;

        try {
            JTable table = new JTable(content, header);
            int heightRow = table.getRowHeight();
            table.setRowHeight(heightRow * 20);
            tablePanel.add(new JScrollPane(table));
            tablePanel.setTitleAt(tab, nameTab);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "File not yet import");
        }
    }

    public static void main(String args[]) {
        homeGUI = new HomeGUI();
        homeGUI.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem actItem;
    private javax.swing.JMenuItem checkItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem preItem;
    private javax.swing.JTabbedPane tablePanel;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
